<?xml version="1.0"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!-- MANDATORY: Change this to your mod id. This will be used as Bepinex plugin GUID and as ModID in About.xml -->
    <ModID>aproposmath-stationeers-profiling</ModID>
    <AssemblyName>StationeersProfiling</AssemblyName>
    <Description>Mod for showing timings of game code functions</Description>
    <!-- Optional: Set this if it's not found automatically or you want to force a specific Stationeers directory -->
    <StationeersDirectory/>
    <Dependencies>
      <!-- Put links to .zip files here, they will be downloaded and extracted to /Template/dependencies before build on Github actions -->
      <!-- <Url>https://some.url/to/some/file.zip</Url> -->
    </Dependencies>
  </PropertyGroup>
</Project>
